<?php
/** Canonical starter-content library shared by WordPress setup and preview QA. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

function cbg_service_library() {
	return array(
		'contractor-websites' => cbg_service( 'Contractor Website Design', 'Contractor websites built to turn local demand into calls and estimate requests.', 'Contractor Website Design | Contractor Build', 'Custom, mobile-first WordPress websites for contractors, with conversion strategy, technical SEO, service pages, tracking, and CRM-ready forms.',
			array( 'Generic templates hide the services and proof customers need.', 'Slow mobile pages lose urgent callers before they reach the estimate form.', 'Disconnected forms make it difficult to attribute and follow up with leads.' ),
			array( 'Information architecture for services and real service areas', 'Custom responsive WordPress design and Gutenberg editing', 'Click-to-call paths, estimate forms, trust content, and project proof', 'Technical SEO, schema-ready markup, analytics, call tracking, and CRM integrations' ),
			'We map the buying journey before wireframes, prototype the highest-value mobile paths, build reusable blocks, and validate speed, accessibility, search markup, forms, and event tracking before launch.',
			'An emergency plumber needs an immediate call path; a remodeler needs portfolios, process detail, qualification, and a longer-consideration form.', array( 'landing-page-design', 'conversion-optimization', 'analytics-tracking' ) ),
		'contractor-seo' => cbg_service( 'Contractor SEO', 'Build durable search visibility for the services and markets that matter.', 'Contractor SEO Services | Contractor Build', 'People-first contractor SEO covering technical health, service content, internal links, authority, local relevance, and measurement.',
			array( 'Important services have no dedicated, useful search destination.', 'Crawling, duplication, or internal-link problems dilute visibility.', 'Reporting celebrates traffic without connecting it to qualified opportunities.' ),
			array( 'Technical crawl, indexation, and Search Console analysis', 'Service, competitor, and search-intent research', 'Original service content and deliberate internal linking', 'Digital PR and relevant authority development', 'Lead-quality and organic landing-page reporting' ),
			'We establish a technical baseline, prioritize commercial topics by business value, improve or create the pages that deserve to rank, strengthen discovery paths, and review search performance alongside calls and forms.',
			'A roofer may separate repair, replacement, inspection, and storm intent; an HVAC company may prioritize no-cool searches in summer and replacement research before peak demand.', array( 'keyword-research', 'service-area-seo', 'competitor-research' ) ),
		'local-seo' => cbg_service( 'Local SEO', 'Strengthen the signals customers and search engines use to understand where you work.', 'Local SEO for Contractors | Contractor Build', 'Local SEO for contractors across websites, Google Maps, citations, reviews, local content, and legitimate service-area relevance.',
			array( 'Business information conflicts across important platforms.', 'Service areas are listed but not supported by useful local evidence.', 'The website and Google Business Profile tell different stories.' ),
			array( 'Local visibility and citation audit', 'NAP and entity consistency', 'Service-area content strategy', 'Local links, reviews, and structured-data guidance', 'Maps and organic performance reporting' ),
			'We verify the real operating footprint, correct high-value inconsistencies, align the website and profile, build useful local content, and monitor visibility without fake locations or ranking guarantees.',
			'A garage-door company can clarify same-day coverage and common repair needs by market without publishing dozens of city-swapped doorway pages.', array( 'google-business-profile', 'service-area-seo', 'reputation-management' ) ),
		'google-ads' => cbg_service( 'Google Ads Management', 'Capture high-intent searches with disciplined targeting and conversion measurement.', 'Google Ads for Contractors | Contractor Build', 'Contractor Google Ads management with search strategy, negative keywords, geo controls, landing pages, call tracking, and transparent optimization.',
			array( 'Broad queries spend budget outside profitable services.', 'Ads send every visitor to a generic homepage.', 'Reported conversions include spam, wrong numbers, and unqualified calls.' ),
			array( 'Search-term and keyword strategy', 'Negative keywords and geographic controls', 'Service-specific ads and landing pages', 'Call, form, and qualified-lead tracking', 'Budget pacing, experiments, and plain-language reporting' ),
			'We define eligible services and geography, build tightly related campaigns, connect each intent to a relevant page, verify conversion signals, and optimize using lead quality—not clicks alone.',
			'An electrician can separate emergency troubleshooting from panels, generators, and EV chargers so budgets and messages reflect different values and urgency.', array( 'landing-page-design', 'call-tracking', 'conversion-optimization' ) ),
		'local-services-ads' => cbg_service( 'Google Local Services Ads', 'Operate eligible LSA campaigns with accurate services, areas, budgets, and lead workflows.', 'Local Services Ads for Contractors | Contractor Build', 'LSA setup and management for eligible contractors, including service configuration, budgets, lead handling, monitoring, and available disputes.',
			array( 'Incorrect services or areas create irrelevant leads.', 'Slow lead handling reduces the value of expensive inquiries.', 'Teams lack a consistent review and dispute workflow.' ),
			array( 'Eligibility and profile-readiness review', 'Service and service-area configuration', 'Budget and schedule planning', 'Lead-status and available dispute workflows', 'Performance and lead-quality monitoring' ),
			'We confirm accurate business information, configure only real services and areas, document response ownership, review lead outcomes, and adjust budgets from observed capacity and quality. Google controls screening, badges, and placement.',
			'Locksmith and plumbing inquiries are time-sensitive; routing and answer speed often matter as much as campaign settings.', array( 'call-tracking', 'reputation-management', 'local-seo' ) ),
		'social-media-advertising' => cbg_service( 'Social Media Advertising', 'Create and recapture local demand through useful offers and creative.', 'Social Media Advertising for Contractors | Contractor Build', 'Facebook and Instagram advertising for contractors, including creative, local audiences, lead forms, landing pages, retargeting, and tracking.',
			array( 'The business relies only on customers already searching.', 'Generic stock creative fails to demonstrate the work.', 'Lead forms create volume without qualification or follow-up.' ),
			array( 'Offer and audience strategy', 'Facebook and Instagram campaign builds', 'Project-led creative and copy', 'Lead forms or landing pages', 'Retargeting, attribution, and lead-quality feedback' ),
			'We match the campaign to the buying cycle, develop credible local creative, control frequency and geography, connect leads to rapid follow-up, and test offers without promising a fixed lead volume.',
			'Remodelers can educate homeowners with project stories; roofers can use storm-season inspection messaging; maintenance businesses can promote timely recurring services.', array( 'retargeting', 'landing-page-design', 'branding' ) ),
		'google-business-profile' => cbg_service( 'Google Business Profile Optimization', 'Make your local profile complete, accurate, useful, and policy-safe.', 'Google Business Profile Optimization | Contractor Build', 'Legitimate Google Business Profile optimization for contractors covering categories, services, photos, posts, reviews, and local alignment.',
			array( 'The primary category does not reflect the core business.', 'Services, hours, and coverage are incomplete or inconsistent.', 'Photos and reviews do not help prospects evaluate the company.' ),
			array( 'Profile and policy audit', 'Eligible category and service configuration', 'Business information and service-area alignment', 'Photo, post, Q&A, and review workflows', 'Website and profile conversion tracking' ),
			'We document the real business, correct inaccurate fields, build a sustainable publishing and photo routine, and connect profile activity to the website. We never use fake locations, reviews, or keyword-stuffed names.',
			'A service-area contractor should hide a residential address when required and accurately represent where crews actually travel.', array( 'local-seo', 'reputation-management', 'service-area-seo' ) ),
		'lead-generation' => cbg_service( 'Contractor Lead Generation', 'Build a balanced acquisition system around qualified opportunities—not list purchases.', 'Contractor Lead Generation | Contractor Build', 'Connected contractor lead generation using search, paid media, landing pages, tracking, qualification, and follow-up.',
			array( 'Lead sources are unpredictable or impossible to attribute.', 'Volume overwhelms the team while quality remains unclear.', 'Marketing and sales use different definitions of a qualified lead.' ),
			array( 'Channel and offer strategy', 'Search, local, and paid-social acquisition', 'Conversion pages and lead qualification', 'Source, call, form, and pipeline tracking', 'Capacity-aware budget and follow-up planning' ),
			'We define a qualified opportunity, select channels around intent and sales cycle, build conversion paths, connect tracking to the pipeline, and reallocate effort using real outcomes.',
			'A high-ticket remodeler may prefer fewer well-qualified consultations, while an emergency plumber needs immediate calls within a tight dispatch radius.', array( 'conversion-optimization', 'marketing-automation', 'analytics-tracking' ) ),
		'reputation-management' => cbg_service( 'Reputation Management', 'Turn honest customer feedback into a consistent operating system.', 'Reputation Management for Contractors | Contractor Build', 'Legitimate contractor review requests, monitoring, response workflows, feedback routing, and reputation reporting without fake reviews.',
			array( 'Review requests depend on technicians remembering.', 'Negative feedback reaches public channels before management sees it.', 'Responses are inconsistent, defensive, or delayed.' ),
			array( 'Customer-feedback and review-request workflow', 'Email and SMS request automation with consent controls', 'Monitoring and response ownership', 'Templates, escalation, and reporting', 'Review placement on eligible website pages' ),
			'We identify the right post-job moment, automate neutral requests to all eligible customers, route feedback, train response owners, and monitor trends. We do not fabricate reviews or gate unhappy customers.',
			'Restoration customers need empathetic responses; recurring service businesses can trigger requests after confirmed successful visits.', array( 'marketing-automation', 'google-business-profile', 'email-sms-follow-up' ) ),
		'marketing-automation' => cbg_service( 'Marketing Automation', 'Respond faster and keep every opportunity moving without losing the human handoff.', 'Marketing Automation for Contractors | Contractor Build', 'Contractor marketing automation for lead routing, missed calls, SMS, email, reminders, pipeline stages, and reactivation.',
			array( 'New inquiries sit in shared inboxes.', 'Missed calls never receive a useful next step.', 'Estimates and older customers receive inconsistent follow-up.' ),
			array( 'CRM and lead-source integration', 'Immediate acknowledgement and routing', 'Missed-call, estimate, and appointment workflows', 'Pipeline stages and task ownership', 'Consent, opt-out, and reactivation controls' ),
			'We map the actual sales process, remove redundant messages, configure triggers and ownership, test every branch, and report where leads stall. Automation supports staff; it does not impersonate them.',
			'An HVAC replacement lead may need financing information and reminders, while an emergency lead needs immediate routing to an available dispatcher.', array( 'crm-integration', 'email-sms-follow-up', 'call-tracking' ) ),
		'analytics-tracking' => cbg_service( 'Analytics & Lead Tracking', 'Connect marketing activity to calls, forms, qualified opportunities, and booked work.', 'Analytics and Lead Tracking for Contractors | Contractor Build', 'GA4, Tag Manager, call and form tracking, attribution, CRM feedback, and contractor marketing dashboards.',
			array( 'Reports count sessions but cannot explain lead quality.', 'Calls and forms are double-counted or assigned to direct traffic.', 'Ad platforms optimize toward shallow events.' ),
			array( 'Measurement plan and event taxonomy', 'GA4 and Tag Manager implementation', 'Call, form, UTM, and landing-page capture', 'CRM outcome feedback and dashboarding', 'Consent-aware QA and anomaly monitoring' ),
			'We define decisions before events, document each conversion, test browser and server paths, exclude internal noise, and reconcile marketing totals with CRM outcomes.',
			'A dashboard can separate raw calls from qualified estimates and show which service, market, and campaign created each opportunity.', array( 'call-tracking', 'crm-integration', 'conversion-optimization' ) ),
		'branding' => cbg_service( 'Contractor Branding & Content', 'Build a credible identity and message customers can recognize and trust.', 'Contractor Branding and Content | Contractor Build', 'Brand strategy, identity, messaging, project content, campaign creative, and practical guidelines for contractor businesses.',
			array( 'The company looks different across trucks, website, and ads.', 'Messaging lists services without explaining why customers should care.', 'Teams lack usable photo, voice, and design standards.' ),
			array( 'Positioning and message framework', 'Logo and visual-system direction', 'Voice, offer, and proof guidance', 'Project photography and content planning', 'Reusable campaign and sales assets' ),
			'We research customers and competitors, identify a defensible position, develop practical identity and voice rules, apply them to high-value touchpoints, and give the team usable templates.',
			'A premium design-build remodeler needs a different voice and proof system than a rapid-response restoration company.', array( 'contractor-websites', 'social-media-advertising', 'competitor-research' ) ),
		'landing-page-design' => cbg_service( 'Contractor Landing Page Design', 'Match one campaign and customer intent to one focused conversion path.', 'Landing Page Design for Contractors | Contractor Build', 'Fast contractor landing pages with message match, proof, qualification, mobile calls, forms, and conversion tracking.', array( 'Campaign traffic lands on a generic homepage.', 'The offer and page headline do not match the ad.', 'Forms ask too much before establishing trust.' ), array( 'Intent-specific message and offer', 'Mobile-first layout and proof', 'Calls, forms, qualification, and thank-you flow', 'Experiment and event setup' ), 'We review the query or audience, remove navigation distractions, sequence proof and objections, build the shortest responsible form, and validate attribution.', 'A water-damage page should prioritize rapid calls and coverage; a kitchen-remodel page should set expectations and qualify project fit.', array( 'google-ads', 'conversion-optimization', 'analytics-tracking' ) ),
		'conversion-optimization' => cbg_service( 'Conversion Optimization', 'Improve the percentage of qualified visitors who take a useful next step.', 'Conversion Optimization for Contractor Websites | Contractor Build', 'Contractor conversion optimization using behavioral evidence, call and form data, UX improvements, and controlled tests.', array( 'Mobile visitors cannot find the primary next step.', 'Proof appears after the point where prospects abandon.', 'Changes are made from opinion instead of evidence.' ), array( 'Journey and friction review', 'Call and form analysis', 'Mobile UX and message improvements', 'Test plan and outcome measurement' ), 'We establish a trustworthy baseline, identify the largest friction points, prioritize changes by impact and effort, and judge results by qualified outcomes.', 'Reducing fields may help emergency leads; adding project qualifiers may improve consultation quality for high-ticket work.', array( 'landing-page-design', 'analytics-tracking', 'call-tracking' ) ),
		'service-area-seo' => cbg_service( 'Service Area SEO', 'Build legitimate local relevance without thin city-swapped pages.', 'Service Area SEO for Contractors | Contractor Build', 'Research-led service-area SEO with useful local pages, internal links, proof, structured data, and performance measurement.', array( 'City pages repeat the same copy.', 'Coverage claims exceed the real operating area.', 'Local pages lack projects, logistics, or service detail.' ), array( 'Market prioritization', 'Unique local intent and competitor research', 'Useful location-page planning', 'Local proof, links, and measurement' ), 'We rank markets by operational value, require unique evidence and customer utility, publish selectively, and improve or remove pages that do not deserve indexation.', 'A roofing market page can discuss local roof stock and storm patterns only when supported by real experience—not automated city insertion.', array( 'local-seo', 'keyword-research', 'contractor-seo' ) ),
		'crm-integration' => cbg_service( 'Contractor CRM Integration', 'Carry source and customer context from first inquiry through the sales pipeline.', 'CRM Integration for Contractors | Contractor Build', 'Connect contractor forms, calls, ads, routing, pipeline stages, and revenue outcomes without losing attribution.', array( 'Leads are retyped between systems.', 'Source data disappears after assignment.', 'Pipeline stages do not reflect the real sales process.' ), array( 'System and field mapping', 'Form, call, and webhook connections', 'Routing and duplicate controls', 'Pipeline and outcome reporting' ), 'We document systems and owners, map minimum necessary data, build and test integrations, handle failures, and train staff on the resulting workflow.', 'A lead can retain campaign, service, landing page, and call recording reference while moving from new inquiry to estimate and won or lost.', array( 'marketing-automation', 'analytics-tracking', 'email-sms-follow-up' ) ),
		'call-tracking' => cbg_service( 'Contractor Call Tracking', 'Understand which marketing creates calls—and which calls become real opportunities.', 'Call Tracking for Contractors | Contractor Build', 'Dynamic number insertion, source attribution, call outcomes, privacy controls, and reporting for contractor marketing.', array( 'Every channel uses the same untracked number.', 'Missed and spam calls count as conversions.', 'Tracking numbers create inconsistent local citations.' ), array( 'Number and routing plan', 'Dynamic number insertion', 'Source and landing-page attribution', 'Call outcomes and quality review' ), 'We preserve the primary business number where local consistency matters, configure source pools, test routing, define outcomes, and connect qualified calls to reporting.', 'Emergency-service campaigns can track answer rate and qualified dispatch opportunities without publishing tracking numbers as permanent business identity.', array( 'analytics-tracking', 'google-ads', 'crm-integration' ) ),
		'retargeting' => cbg_service( 'Contractor Retargeting', 'Stay useful to qualified prospects during longer decisions without chasing everyone.', 'Retargeting for Contractors | Contractor Build', 'Consent-aware Google and Meta retargeting for contractor prospects using segmented audiences, credible creative, frequency controls, and measurement.', array( 'Every visitor receives the same repetitive ad.', 'Existing customers and converters remain in prospect campaigns.', 'Creative adds pressure instead of answering objections.' ), array( 'Audience and exclusion plan', 'Google and Meta implementation', 'Sequential creative and project proof', 'Frequency and conversion measurement' ), 'We define eligible audiences, exclude converters where appropriate, segment by intent and recency, rotate useful creative, and monitor assisted conversions.', 'A remodeler can show process and project proof during a long decision; emergency services usually need shorter windows and tighter exclusions.', array( 'social-media-advertising', 'google-ads', 'analytics-tracking' ) ),
		'email-sms-follow-up' => cbg_service( 'Email & SMS Follow-Up', 'Create timely, consent-aware communication around inquiries, estimates, and appointments.', 'Email and SMS Follow-Up for Contractors | Contractor Build', 'Contractor email and SMS workflows for lead acknowledgement, estimate follow-up, reminders, reactivation, consent, and opt-outs.', array( 'Prospects receive no confirmation after submitting.', 'Estimate follow-up depends on memory.', 'Messages ignore consent, timing, or ownership.' ), array( 'Message and consent mapping', 'Acknowledgement and routing', 'Estimate and appointment sequences', 'Opt-out, quiet-hour, and handoff controls' ), 'We map approved contact reasons, write concise messages, configure timing and ownership, test replies and opt-outs, and review where human follow-up is required.', 'A missed-call text can acknowledge the call and ask for service context; it should not pretend a technician has reviewed the problem.', array( 'marketing-automation', 'crm-integration', 'reputation-management' ) ),
		'competitor-research' => cbg_service( 'Contractor Competitor Research', 'Understand the local choices customers see before deciding where to compete.', 'Competitor Research for Contractors | Contractor Build', 'Contractor competitor research across positioning, services, search visibility, ads, offers, reviews, content, and conversion experience.', array( 'Strategy copies the loudest competitor.', 'National brands are compared with unrelated local operators.', 'Research stops at keyword rankings.' ), array( 'Real search-result and market set', 'Service, offer, and message comparison', 'Organic, Maps, paid, and review observations', 'Opportunity and risk brief' ), 'We define true competitors by service and geography, document what customers encounter, distinguish evidence from assumptions, and turn gaps into prioritized tests—not imitation.', 'A fencing company may discover competitors ignore commercial work, while a roofer may find estimate speed and financing dominate paid messages.', array( 'keyword-research', 'contractor-seo', 'branding' ) ),
		'keyword-research' => cbg_service( 'Contractor Keyword Research', 'Translate how customers search into useful pages, campaigns, and measurement.', 'Keyword Research for Contractors | Contractor Build', 'Contractor keyword research organized by service, urgency, intent, geography, seasonality, and business value.', array( 'One broad keyword represents several different needs.', 'High-volume terms receive priority despite poor fit.', 'Organic and paid teams use conflicting intent maps.' ), array( 'Service and customer-language discovery', 'Intent, urgency, and funnel classification', 'Local result and competitor review', 'Page and campaign mapping' ), 'We combine business input, search-result evidence, performance data, and customer language, then map topics to existing or justified new destinations.', '“AC repair,” “AC replacement,” and “HVAC maintenance” need different answers, economics, and conversion paths even when tools group them together.', array( 'contractor-seo', 'google-ads', 'competitor-research' ) ),
	);
}

function cbg_service( $title, $tagline, $seo_title, $meta, $problems, $included, $process, $example, $related ) {
	return compact( 'title', 'tagline', 'seo_title', 'meta', 'problems', 'included', 'process', 'example', 'related' );
}

function cbg_industry_library() {
	$items = array(
		'locksmith-marketing' => array( 'Locksmith Marketing', 'Emergency intent, trust, mobile speed, accurate service areas, Maps and eligible LSA visibility define locksmith acquisition.', array( 'Lockouts and urgent calls require immediate mobile paths.', 'Policy compliance and real local identity are essential.', 'Call answer rate and dispatch radius determine usable demand.' ), array( 'Emergency service pages and click-to-call UX', 'Policy-safe local and paid visibility', 'Call quality, routing, and after-hours measurement' ) ),
		'roofing-marketing' => array( 'Roofing Marketing', 'Roofing growth must balance storm demand, urgent repairs, planned replacement, insurance questions, and high-ticket estimate follow-up.', array( 'Demand changes sharply by weather and season.', 'Repair, replacement, inspection, and commercial intent differ.', 'Long estimate cycles require visible follow-up ownership.' ), array( 'Service and storm-intent search architecture', 'Project proof, financing context, and estimate conversion', 'Lead-source, inspection, estimate, and sold-job feedback' ) ),
		'hvac-marketing' => array( 'HVAC Marketing', 'HVAC acquisition spans emergency no-cool calls, seasonal maintenance, indoor air quality, and considered system replacement.', array( 'Peak weather can exceed dispatch capacity.', 'Repair and replacement economics require different campaigns.', 'Maintenance customers create valuable recurring demand.' ), array( 'Seasonal search and budget planning', 'Emergency, replacement, and maintenance conversion paths', 'Booking, call, financing, and reactivation workflows' ) ),
		'plumber-marketing' => array( 'Plumber Marketing', 'Plumbing marketing must route urgent leaks and stoppages alongside water heaters, repiping, fixtures, and planned work.', array( 'Mobile customers need immediate clarity and calls.', 'Broad campaigns can attract DIY and irrelevant queries.', 'Dispatch coverage and job type affect lead value.' ), array( 'Emergency and planned-service page separation', 'Maps, organic, LSA, and paid-search coordination', 'Call outcomes and service-area controls' ) ),
		'electrician-marketing' => array( 'Electrician Marketing', 'Electrical demand ranges from troubleshooting to panels, generators, EV chargers, lighting, and rewiring.', array( 'Service values and sales cycles vary widely.', 'Safety and licensing context influence trust.', 'Emerging services need education as well as capture.' ), array( 'Service-line search architecture', 'Trust, scope, and estimate content', 'Campaign segmentation by urgency and value' ) ),
		'general-contractor-marketing' => array( 'General Contractor Marketing', 'General contractors need qualified project pipelines built on credibility, scope fit, project evidence, and longer-consideration nurture.', array( 'Broad “contractor” traffic often lacks project fit.', 'Buyers evaluate process and proof before contact.', 'Long cycles make first-touch attribution incomplete.' ), array( 'Positioning by project type and ideal fit', 'Portfolio, process, and qualification experiences', 'Consultation, estimate, and pipeline measurement' ) ),
		'remodeling-marketing' => array( 'Remodeling Marketing', 'Remodeling customers compare aesthetics, trust, process, investment fit, and project experience over a long research journey.', array( 'Generic galleries fail to explain scope or thinking.', 'Unqualified inquiries consume design and sales time.', 'Retargeting and nurture matter before consultation.' ), array( 'Kitchen, bath, and whole-home content strategy', 'Project stories and qualification', 'Consultation nurture and source-to-sale tracking' ) ),
		'garage-door-marketing' => array( 'Garage Door Company Marketing', 'Garage-door companies balance urgent repairs with planned door replacement and installation.', array( 'Repair searches are urgent and mobile.', 'Replacement buyers need visual and product guidance.', 'Service radius and same-day capacity shape campaigns.' ), array( 'Repair and installation intent separation', 'Local visibility and call-first pages', 'Schedule, call, and job-type tracking' ) ),
		'landscaping-marketing' => array( 'Landscaping Marketing', 'Landscapers often serve recurring maintenance and high-value design-build work with different audiences and economics.', array( 'Seasonality changes both demand and capacity.', 'Maintenance and construction should not share one offer.', 'Visual proof and property fit drive confidence.' ), array( 'Service-line and seasonal campaign planning', 'Project galleries with useful context', 'Recurring lead and design-consultation workflows' ) ),
		'painting-marketing' => array( 'Painting Contractor Marketing', 'Painting customers evaluate scope, preparation, finish quality, scheduling, and trust for residential or commercial work.', array( 'Price-only messages attract poor-fit estimates.', 'Interior, exterior, cabinet, and commercial intent differ.', 'Before-and-after proof needs scope context.' ), array( 'Service-specific pages and estimate paths', 'Project proof and preparation education', 'Local search, paid demand, and estimate follow-up' ) ),
		'pest-control-marketing' => array( 'Pest Control Marketing', 'Pest control acquisition mixes urgent infestations, pest-specific research, recurring plans, seasonality, and safety questions.', array( 'Pest and treatment intent varies by season.', 'One-time and recurring economics differ.', 'Customers need fast reassurance and clear next steps.' ), array( 'Pest-specific educational landing paths', 'Seasonal local and paid strategy', 'Booking, plan conversion, and reactivation' ) ),
		'moving-company-marketing' => array( 'Moving Company Marketing', 'Moving leads are date-, origin-, destination-, inventory-, and service-dependent, making qualification and rapid quoting critical.', array( 'Broad lead marketplaces create price competition.', 'Dates and service boundaries determine fit.', 'Trust and review signals carry unusual weight.' ), array( 'Local, long-distance, and specialty separation', 'Quote qualification and rapid response', 'Source, booked move, value, and review tracking' ) ),
		'restoration-marketing' => array( 'Restoration Company Marketing', 'Restoration demand is urgent, event-driven, trust-sensitive, and often involves insurance and complex service categories.', array( 'Water, fire, mold, and reconstruction intent differ.', 'Answer speed matters during stressful events.', 'Claims language must remain accurate and responsible.' ), array( '24/7 mobile call and routing experience', 'Service-specific local and paid coverage', 'Call, dispatch, job, and source feedback' ) ),
		'concrete-marketing' => array( 'Concrete Contractor Marketing', 'Concrete customers need clear project capabilities, site and access expectations, visual proof, and efficient scope qualification.', array( 'Residential and commercial opportunities differ.', 'Small poor-fit requests can overwhelm estimating.', 'Photos without scope details provide weak proof.' ), array( 'Project-type pages and qualification', 'Context-rich project galleries', 'Estimate pipeline and source measurement' ) ),
		'flooring-marketing' => array( 'Flooring Contractor Marketing', 'Flooring acquisition combines material research, installation expertise, in-home measurement, commercial scope, and visual choice.', array( 'Material and installation searches overlap.', 'Showroom and service-area journeys differ.', 'Samples and estimates extend the buying cycle.' ), array( 'Material and project-specific content', 'Measurement or consultation conversion', 'Remarketing and estimate follow-up' ) ),
		'fencing-marketing' => array( 'Fencing Company Marketing', 'Fence buyers compare material, privacy, security, property constraints, lead times, and installation quality.', array( 'Wood, vinyl, aluminum, chain-link, and commercial intent differ.', 'Property and access details affect estimates.', 'Visual proof should show material and project context.' ), array( 'Material and use-case search pages', 'Photo-led estimate experience', 'Service-area, quote, and sold-job tracking' ) ),
		'pool-company-marketing' => array( 'Pool Company Marketing', 'Pool businesses may combine long-cycle construction, renovation, repair, and recurring service with strong seasonality.', array( 'Construction and service are different funnels.', 'Design inspiration precedes consultation.', 'Seasonal capacity requires careful budget pacing.' ), array( 'Construction, renovation, and service separation', 'Project stories and consultation qualification', 'Seasonal nurture and pipeline measurement' ) ),
		'cleaning-company-marketing' => array( 'Cleaning Company Marketing', 'Cleaning companies balance local trust, recurring schedules, one-time services, commercial needs, and route density.', array( 'Recurring and one-time leads have different value.', 'Coverage should support efficient routes.', 'Trust and consistency matter inside customer properties.' ), array( 'Residential, specialty, and commercial paths', 'Local booking and quote experience', 'Recurring conversion and review workflows' ) ),
		'solar-contractor-marketing' => array( 'Solar Contractor Marketing', 'Solar marketing requires education, qualification, finance clarity, long-cycle follow-up, and careful compliance.', array( 'Low-friction lead forms can create low-intent volume.', 'Home, roof, utility, and finance fit affect qualification.', 'Savings and incentive claims require substantiation.' ), array( 'Educational and qualification content', 'Consent-aware paid acquisition and nurture', 'Appointment, proposal, and sold-system reporting' ) ),
	);
	$out = array();
	foreach ( $items as $slug => $item ) {
		$out[ $slug ] = array( 'title' => $item[0], 'tagline' => $item[1], 'seo_title' => $item[0] . ' | Contractor Build', 'meta' => $item[1] . ' Build a measurable website, search, advertising, tracking, and follow-up system.', 'challenges' => $item[2], 'strategy' => $item[3] );
	}
	return $out;
}

function cbg_render_service_content( $data ) {
	$faq = array(
		array( 'How quickly should this work produce results?', 'Timing depends on the starting point, market, channel, budget, and sales process. We set leading indicators and review qualified opportunities rather than promising a fixed result.' ),
		array( 'How will performance be measured?', 'Measurement is agreed before launch and can include qualified calls, forms, appointments, estimates, pipeline value, and sold work when CRM data is available.' ),
		array( 'Can this work with our existing website and systems?', 'Often, yes. We audit what is already useful, identify integration constraints, and recommend replacement only when the evidence supports it.' ),
	);
	$html = '<h2>What this service solves</h2><p>' . esc_html( $data['tagline'] ) . ' Contractor Build approaches the work as part of the complete customer-acquisition system, so the message, traffic source, conversion experience, tracking, and follow-up support the same business goal.</p>';
	$html .= cbg_html_list( $data['problems'] );
	$html .= '<h2>What is included</h2>' . cbg_html_list( $data['included'] );
	$html .= '<h2>Our contractor-first process</h2><p>' . esc_html( $data['process'] ) . '</p>';
	$html .= '<h2>How this looks in practice</h2><p>' . esc_html( $data['example'] ) . '</p>';
	$html .= '<h2>Related growth capabilities</h2><p>';
	$library = cbg_service_library();
	foreach ( $data['related'] as $slug ) { if ( isset( $library[ $slug ] ) ) { $html .= '<a href="' . esc_url( home_url( '/services/' . $slug . '/' ) ) . '">' . esc_html( $library[ $slug ]['title'] ) . '</a> · '; } }
	$html .= '<a href="' . esc_url( home_url( '/free-marketing-audit/' ) ) . '">Request a free marketing audit</a></p><h2>Frequently asked questions</h2>';
	foreach ( $faq as $row ) { $html .= '<h3>' . esc_html( $row[0] ) . '</h3><p>' . esc_html( $row[1] ) . '</p>'; }
	return $html;
}

function cbg_render_industry_content( $data ) {
	$html = '<h2>The customer-acquisition realities in this industry</h2><p>' . esc_html( $data['tagline'] ) . ' The right plan reflects actual service capacity, geography, margins, urgency, seasonality, and the steps between an inquiry and a completed job.</p>';
	$html .= cbg_html_list( $data['challenges'] );
	$html .= '<h2>Recommended marketing system</h2>' . cbg_html_list( $data['strategy'] );
	$html .= '<h2>Website, search, and paid-media priorities</h2><p>We connect useful service content, legitimate local relevance, campaign-specific conversion paths, call and form attribution, and timely follow-up. Channel investment is adjusted using qualified opportunities and operational capacity—not rankings or clicks in isolation.</p>';
	$html .= '<h2>How we measure progress</h2><p>Reporting can connect source and landing page to qualified calls, forms, booked appointments, estimates, and sold work when the underlying systems make those outcomes available. We do not invent benchmarks or guarantee lead volume.</p>';
	$html .= '<h2>Frequently asked questions</h2><h3>Which channel should we start with?</h3><p>The answer depends on existing demand, competitive results, capacity, sales cycle, and measurement readiness. The audit identifies the largest practical constraint before recommending a channel.</p><h3>Do you create city pages?</h3><p>Only where a page has a legitimate audience and can provide unique local value. We do not publish thin city-name variants.</p><p><a href="' . esc_url( home_url( '/free-marketing-audit/' ) ) . '">Get an industry-specific marketing audit</a> or explore <a href="' . esc_url( home_url( '/services/' ) ) . '">all growth services</a>.</p>';
	return $html;
}

function cbg_html_list( $items ) {
	$html = '<ul>';
	foreach ( $items as $item ) { $html .= '<li>' . esc_html( $item ) . '</li>'; }
	return $html . '</ul>';
}
