<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

function cbg_create_starter_content() {
	if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'cbg_create_starter_content' ) ) { wp_die( 'Unauthorized request.' ); }
	$pages = array(
		'About' => array( 'about', '<h2>Your outsourced digital growth department</h2><p>Contractor Build connects the website, search visibility, advertising, lead tracking, and follow-up contractors need to create a more dependable pipeline.</p><h2>Why one connected team matters</h2><p>When every vendor owns one small piece, reporting conflicts and opportunities fall through the gaps. We create one plan, agree on meaningful measurements, and optimize the whole customer journey.</p><h2>Our process</h2><p><strong>Audit. Build. Launch. Optimize. Scale.</strong> Each engagement starts with the market and the business—not a prebuilt package.</p>' ),
		'Contact' => array( 'contact', '<h2>Tell us where you want to grow</h2><p>Share your goals, current challenges, core services, and service area. We will respond with the right next step.</p>[contractor_build_audit_form]' ),
		'Free Marketing Audit' => array( 'free-marketing-audit', '<h2>Find the leaks in your customer acquisition system</h2><p>We will review your website, search presence, paid media, conversion paths, and follow-up process. You will get practical priorities—not a recycled scorecard.</p>[contractor_build_audit_form]' ),
		'Privacy Policy' => array( 'privacy-policy', '<h2>Privacy policy</h2><p><strong>Draft notice:</strong> Have qualified counsel review this policy before launch. Describe collected data, purposes, vendors, retention, user choices, and applicable regional rights.</p>' ),
		'Terms' => array( 'terms', '<h2>Website terms</h2><p><strong>Draft notice:</strong> Have qualified counsel prepare and approve these terms before launch.</p>' ),
		'Accessibility' => array( 'accessibility', '<h2>Our accessibility commitment</h2><p>Contractor Build aims to provide an inclusive digital experience. If you encounter an accessibility barrier, contact us and describe the page and issue so we can help.</p>' ),
	);
	$home_id = 0;
	foreach ( $pages as $title => $data ) {
		$id = cbg_upsert_content( 'page', $title, $data[0], $data[1], '' );
		if ( 'About' === $title && ! $home_id ) { $home_id = $id; }
	}
	$services = cbg_service_content();
	foreach ( $services as $slug => $data ) { cbg_upsert_content( 'service', $data[0], $slug, $data[1], $data[2] ); }
	$industries = cbg_industry_content();
	foreach ( $industries as $slug => $data ) { cbg_upsert_content( 'industry', $data[0], $slug, $data[1], $data[2] ); }
	foreach ( array( 'Contractor Marketing', 'Contractor SEO', 'Google Ads', 'Local SEO', 'Web Design', 'Social Media', 'Lead Generation', 'Business Growth' ) as $term ) { if ( ! term_exists( $term, 'resource_category' ) ) { wp_insert_term( $term, 'resource_category' ); } }
	flush_rewrite_rules();
	wp_safe_redirect( add_query_arg( 'starter_content', 'created', admin_url( 'admin.php?page=contractor-build' ) ) ); exit;
}
add_action( 'admin_post_cbg_create_starter_content', 'cbg_create_starter_content' );

function cbg_upsert_content( $type, $title, $slug, $content, $excerpt ) {
	$existing = get_page_by_path( $slug, OBJECT, $type );
	if ( $existing ) { return $existing->ID; }
	return wp_insert_post( array( 'post_type' => $type, 'post_title' => $title, 'post_name' => $slug, 'post_content' => $content, 'post_excerpt' => $excerpt, 'post_status' => 'publish' ), true );
}

function cbg_service_content() {
	$base = '<h2>Build around qualified opportunities</h2><p>Our strategy starts with your services, margins, capacity, market, sales process, and current performance. From there, we build the assets and measurement needed to improve decisions over time.</p><h2>What the work includes</h2><ul><li>Discovery and competitor research</li><li>Customer journey and conversion planning</li><li>Implementation by a contractor-focused team</li><li>Call, form, and campaign measurement</li><li>Transparent performance reviews</li><li>Ongoing testing and prioritization</li></ul><h2>Measurement without empty promises</h2><p>No ethical marketing partner can guarantee rankings, lead volume, or revenue. We define useful indicators, track what can be measured, and use the evidence to improve the system.</p>';
	return array(
		'contractor-websites' => array( 'Contractor Website Design', '<h2>A website that helps customers take the next step</h2><p>We build custom, mobile-first WordPress websites around calls, estimate requests, services, and service areas. The foundation includes semantic templates, technical SEO, fast assets, accessible forms, analytics hooks, XML sitemap support, canonical compatibility, secure coding practices, and CRM-ready lead capture.</p><h3>Built into every website plan</h3><ul><li>Conversion-focused information architecture</li><li>Service and location page systems</li><li>Responsive design and clear calls to action</li><li>Schema where eligible and useful</li><li>Image, cache, and Core Web Vitals planning</li><li>Search Console, analytics, call tracking, and CRM integration</li></ul>' . $base, 'SEO-ready WordPress websites designed to generate calls and estimate requests.' ),
		'contractor-seo' => array( 'Contractor SEO', '<h2>Earn visibility across the customer journey</h2><p>Contractor SEO combines technical health, keyword and competitor research, helpful service content, on-page optimization, internal linking, local relevance, digital PR, and Search Console analysis.</p><h3>SEO workstreams</h3><ul><li>Technical crawling and indexation</li><li>Service and search-intent research</li><li>Original service and location content</li><li>On-page structure and internal links</li><li>Authority building and relevant digital PR</li><li>Search Console reporting and prioritization</li></ul>' . $base, 'People-first SEO for contractors, construction companies, and home-service brands.' ),
		'local-seo' => array( 'Local SEO', '<h2>Strengthen the signals behind local discovery</h2><p>We improve the consistency and usefulness of your website, Google Business Profile, service-area content, citations, reviews, structured data, and relevant local links. We never use fake locations, fake reviews, or misleading business names.</p>' . $base, 'Build legitimate local relevance across your website, Maps presence, reviews, and citations.' ),
		'google-ads' => array( 'Google Ads Management', '<h2>Capture high-intent demand with control</h2><p>Campaigns include search strategy, negative keywords, geographic targeting, relevant ad copy, landing pages, call and conversion tracking, remarketing, budget allocation, search-term review, and clear reporting.</p>' . $base, 'Google Ads for contractors focused on qualified calls, forms, and transparent optimization.' ),
		'local-services-ads' => array( 'Google Local Services Ads', '<h2>Manage local lead flow responsibly</h2><p>We support eligible contractors with setup, service configuration, service areas, budget planning, lead management, available dispute workflows, and performance monitoring. Google alone controls eligibility, approval, badges, and placement.</p>' . $base, 'Setup, lead workflows, budgets, and monitoring for eligible Local Services Ads accounts.' ),
		'social-media-advertising' => array( 'Social Media Advertising', '<h2>Create demand in your service area</h2><p>Facebook and Instagram campaigns can introduce the right offer before someone searches. We combine local audiences, useful creative, lead forms, landing pages, retargeting, and conversion tracking.</p>' . $base, 'Meta advertising that helps contractors build awareness, generate leads, and retarget demand.' ),
		'google-business-profile' => array( 'Google Business Profile Optimization', '<h2>A complete, accurate local presence</h2><p>We align eligible categories, services, business information, photos, posts, questions, and review workflows with your real-world operation and Google policies. We never use fake locations, fake reviews, or keyword-stuffed business names.</p>' . $base, 'Policy-safe Google Business Profile strategy for contractors and service-area businesses.' ),
		'reputation-management' => array( 'Reputation Management', '<h2>Make honest customer feedback part of the process</h2><p>Build consistent review requests, automated follow-up, monitoring, response workflows, feedback routing, and clear dashboards. We do not sell, fabricate, or selectively gate reviews.</p>' . $base, 'Legitimate review generation, monitoring, response workflows, and customer feedback systems.' ),
		'marketing-automation' => array( 'Marketing Automation', '<h2>Follow up while the opportunity is fresh</h2><p>Connect CRM intake, lead routing, missed-call workflows, SMS, email, appointment reminders, pipeline stages, and reactivation campaigns. Messaging workflows should use documented consent and honor opt-out requirements.</p>' . $base, 'CRM-connected lead routing, follow-up, reminders, pipeline tracking, and reactivation.' ),
		'lead-generation' => array( 'Contractor Lead Generation', $base, 'A connected mix of search, paid media, landing pages, tracking, and follow-up.' ),
		'analytics-tracking' => array( 'Analytics & Lead Tracking', $base, 'Understand which channels create calls, forms, appointments, and qualified opportunities.' ),
		'branding' => array( 'Contractor Branding & Content', $base, 'Build a recognizable identity and useful content that earns trust in your market.' ),
	);
}

function cbg_industry_content() {
	return array(
		'roofing-marketing' => array( 'Roofing Marketing', '<h2>Compete across urgent repairs and planned replacements</h2><p>Roofing demand shifts with storms, insurance activity, seasonality, and local housing stock. A strong system separates repair, replacement, inspection, commercial, and storm-related intent while protecting lead quality.</p><h2>Recommended roofing growth system</h2><ul><li>Fast mobile pages for repair and replacement intent</li><li>Service-area SEO built on real market knowledge</li><li>Search and Local Services Ads where eligible</li><li>Call tracking and storm-campaign attribution</li><li>Estimate follow-up and review requests</li></ul>', 'Websites, SEO, paid media, and follow-up shaped around the roofing customer journey.' ),
		'hvac-marketing' => array( 'HVAC Marketing', '<h2>Balance emergency demand, maintenance, and replacement</h2><p>HVAC marketing needs to address urgent no-cool and no-heat searches, high-consideration system replacement, seasonal tune-ups, financing questions, and recurring maintenance plans.</p><h2>Recommended HVAC growth system</h2><ul><li>Clear emergency and replacement conversion paths</li><li>Local SEO by legitimate service area</li><li>Seasonal paid-search budget planning</li><li>Call, booking, and job-type tracking</li><li>Maintenance reminders and reactivation</li></ul>', 'Generate and convert HVAC demand across repairs, replacement, and maintenance.' ),
		'plumber-marketing' => array( 'Plumber Marketing', '<h2>Win high-intent local searches without wasting dispatch capacity</h2><p>Plumbing demand ranges from immediate leaks and clogs to water heaters and planned repiping. Campaign structure and page content should route each need to a clear, mobile-first next step.</p><h2>Recommended plumbing growth system</h2><ul><li>Emergency click-to-call experiences</li><li>Distinct pages for valuable service lines</li><li>Maps, organic, paid search, and LSA coverage</li><li>Service-area and schedule controls</li><li>Call quality and booked-job feedback</li></ul>', 'A local acquisition system shaped around urgent and planned plumbing services.' ),
		'electrician-marketing' => array( 'Electrician Marketing', '<h2>Connect homeowners with the right electrical service</h2><p>Customers search differently for emergency troubleshooting, panels, EV chargers, generators, lighting, and rewiring. Useful pages and campaign segmentation improve relevance and routing.</p>', 'Marketing for residential and commercial electrical service demand.' ),
		'locksmith-marketing' => array( 'Locksmith Marketing', '<h2>Build trust at the moment of urgent need</h2><p>Locksmith marketing depends on fast mobile experiences, clear service boundaries, real local credibility, accurate business information, call quality, and policy-compliant advertising.</p>', 'Policy-conscious local marketing for legitimate locksmith businesses.' ),
		'remodeling-marketing' => array( 'Remodeling Marketing', '<h2>Support a longer, visual buying journey</h2><p>Remodeling clients research portfolios, process, trust, budget fit, design capabilities, and project types before reaching out. Content, photography, project stories, qualification, and nurture matter more than urgency.</p>', 'A trust-rich marketing system for kitchen, bathroom, and whole-home remodeling.' ),
		'landscaping-marketing' => array( 'Landscaping Marketing', '<h2>Balance recurring service and high-value projects</h2><p>Landscape maintenance, design-build, irrigation, hardscaping, and seasonal services require different offers, search terms, visuals, and follow-up.</p>', 'Local visibility and lead generation for landscape service and design-build companies.' ),
		'concrete-marketing' => array( 'Concrete Contractor Marketing', '<h2>Show the work and qualify the project</h2><p>Concrete customers need clear project capabilities, service boundaries, proof of workmanship, timing expectations, and a simple way to describe the site and scope.</p>', 'Web, SEO, and paid acquisition for residential and commercial concrete work.' ),
		'general-contractor-marketing' => array( 'General Contractor Marketing', '<h2>Earn confidence for complex projects</h2><p>General contractors need a clear market position, strong project evidence, detailed capabilities, geographic relevance, and a qualification process suited to longer sales cycles.</p>', 'A credible digital growth system for general contractors and construction firms.' ),
	);
}
